site_name: IoT Agent ISOXML/ADAPT
site_url: https://fiware-isoxml.readthedocs.org
repo_url: https://github.com/FIWARE/iotagent-isoxml
site_description: IoT Agent for ISOXML/ADAPT Documentation
docs_dir: docs
site_dir: html
edit_uri: edit/master/docs/
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_iot.css"]
pages:
  - Home: 'index.md'
  - 'User & Programmers Manual':
    - 'API Walkthrough & Development intro': 'usermanual.md'
  - 'Installation & Administration Manual': 
    - 'Installation Guide': 'installationguide.md'
    - 'Operations (logs & alarms)': 'operations.md'
    
